version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/**"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    groups:
      go-deps:
        patterns: ["*"]
        update-types: ["minor", "patch"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
    groups:
      gha:
        patterns: ["*"]
