name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Lint
        run: |
          make lint

      - name: Install dependencies
        run: |
          make tidy

      - name: Build
        run: |
          make build/linux

      - name: Unit Test
        run: go test -v ./...

  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write
